Revert "Fix python 3 deprecation warning"
https://github.com/josefahmad/mongo-shardkey-tools/issues/2

This reverts commit 82701b07a5e687aa1ff44e4e7069327c5d4282a9.

Reverting because on python 2.7 it throws
  TypeError: 'Collection' object is not callable. If you meant
  to call the 'count_documents' method on a 'Collection' object
  it is failing because no such method exists.